Repository nextcloud/twofactor_totp, pull requests merged in 2019-12, with the labels that each got.

#750 Add php7.4 support, drop 7.1, add nightly testing
  .github/workflows/lint.yml
  .travis.yml
  appinfo/info.xml
Labels: 3. to review, enhancement

#754 Allow CI failure with php nightly
  .travis.yml
Labels: 4. to release, bug, technical debt

#775 add andOTP
  README.md
Labels: 3. to review
