Repository nextcloud/twofactor_totp, pull requests merged in 2019-09, with the labels that each got.

#672 Target the beta3
  composer.json
  composer.lock
Labels: 3. to review

#679 Bump master to 18
  appinfo/info.xml
Labels: 3. to review, enhancement

#691 Use the proper IEventDispatcher
  lib/Service/Totp.php
Labels: 3. to review, bug

#693 Redirect questions to help
  .github/ISSUE_TEMPLATE/question.md
Labels: 3. to review
