Repository nextcloud/twofactor_totp, pull requests merged in 2019-03, with the labels that each got.

#485 Fix first migration from an old database schema
  appinfo/info.xml
  lib/Migration/Version020102Date20190304124405.php
Labels: 3. to review, bug

#492 Release v2.1.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 2. developing

#489 Move to rullzer/easytotp
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
  lib/Db/TotpSecret.php
  lib/Db/TotpSecretMapper.php
  lib/Migration/Version030000Date20190305114917.php
  lib/Service/Totp.php
Labels: 2. developing, dependencies, enhancement

#504 Generate TOTP secret using secure random
  composer.json
  lib/Service/Totp.php
Labels: 4. to release, technical debt

#508 Swith to client-side QR lib
  composer.json
  composer.lock
  lib/Controller/SettingsController.php
  package-lock.json
  package.json
  src/components/PersonalTotpSettings.vue
  src/store.js
  tests/Unit/Controller/SettingsControllerTest.php
Labels: 3. to review, enhancement, technical debt

#509 remove invalid use
  lib/Controller/SettingsController.php
Labels: 3. to review
