Repository nextcloud/twofactor_totp, pull requests merged in 2019-08, with the labels that each got.

#632 Release v3.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: 3. to review

#598 Use nextcloud-router for routing
  package-lock.json
  package.json
  src/store.js
  src/tests/setup.js
Labels: 3. to review, enhancement, technical debt

#640 Release v3.0.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#643 Require Nextcloud 17
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review, enhancement

#644 Apply and enforce eslint
  .eslintrc.js
  .travis.yml
  package-lock.json
  package.json
  src/components/PersonalTotpSettings.vue
  src/components/SetupConfirmation.vue
  src/main-settings.js
  src/store.js
  src/tests/components/PersonalTotpSettings.spec.js
  src/tests/setup.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
  src/webpack.test.js
Labels: 3. to review, enhancement

#656 Release v4.0.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#659 Move to our fancy new dispatcher
  lib/AppInfo/Application.php
  lib/Event/StateChanged.php
  lib/Listener/IListener.php
  lib/Listener/StateChangeActivity.php
  lib/Listener/StateChangeRegistryUpdater.php
Labels: 4. to release, enhancement

#662 Fix events unit test
  tests/Unit/Listener/StateChangeRegistryUpdaterTest.php
Labels: 3. to review, bug
