Repository nextcloud/twofactor_totp, pull requests merged in 2022-10, with the labels that each got.

#1248 Update npm and node engines versions
  package.json
Labels: dependencies

#1282 Bump master version to a semantical 8.0.0-alpha0
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review, technical debt

#1281 [stable6.4] Add user deletion cleanup
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Command/CleanUp.php
  lib/Db/TotpSecretMapper.php
  lib/Listener/UserDeleted.php
  package-lock.json
  package.json
  tests/Acceptance/TOTPAcceptanceTest.php
Labels: bug, 3. to review

#1286 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#1287 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#1288 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#1285 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#1289 Specify Postgres 14 in test workflow
  .github/workflows/test.yml
Labels: 3. to review
