Repository nextcloud/twofactor_totp, pull requests merged in 2022-04, with the labels that each got.

#1198 Move to global configs
  .babelrc.js
  .eslintrc.js
  .github/workflows/command-rebase.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  .php-cs-fixer.dist.php
  babel.config.js
  composer.json
  composer.lock
  css/style.css
  package-lock.json
  package.json
  src/components/LoginSetup.vue
  src/components/PersonalTotpSettings.vue
  src/components/SetupConfirmation.vue
  src/logger.js
  src/main-login-setup.js
  src/main-settings.js
  src/services/StateService.js
  src/state.js
  src/store.js
  src/tests/components/PersonalTotpSettings.spec.js
  src/tests/jest.setup.js
  src/tests/setup.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
  stylelint.config.js
  templates/loginsetup.php
  templates/personal.php
  webpack.config.js
Labels: 4. to release, dependencies, technical debt

#1199 Update workflows triggers
  .github/workflows/node-test.yml.orig
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: enhancement, 3. to review

#1203 Remove unused @vue/babel-preset-app
  package-lock.json
  package.json
Labels: 3. to review, dependencies, technical debt

#1196 Update master php testing versions
  .github/workflows/lint-php.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
Labels: 4. to release

#1207 6.3.0-beta.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1197 Adjust phpunit config
  tests/phpunit.xml
Labels: 3. to review

#1208 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies
