Repository nextcloud/twofactor_totp, pull requests merged in 2022-06, with the labels that each got.

#1228 Drop PHP7.3
  .github/workflows/lint-php.yml
  .github/workflows/test.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 2. developing

#1229 Drop Nextcloud 21 support
  .github/workflows/static-analysis.yml
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 3. to review

#1227 Add PHP8.1 support
  .github/workflows/test.yml
  appinfo/info.xml
Labels: 3. to review

#1230 Add PHP8.2 lint job
  .github/workflows/lint-php.yml
Labels: 3. to review

#1226 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#1225 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies
