Repository nextcloud/twofactor_totp, pull requests merged in 2023-04, with the labels that each got.

#1344 chore(deps): Add renovate bot config
  .github/renovate.json
Labels: 3. to review

#1357 chore(deps): Fix renovate base branch
  .github/renovate.json
Labels: 3. to review

#1369 chore(deps): Drop stable24 from Renovate config
  .github/renovate.json
Labels: 3. to review

#1370 chore(deps): Drop Dependabot
  .github/dependabot.yml
  .github/workflows/dependabot-approve-merge.yml
Labels: 4. to release, dependencies

#1375 [stable26] fix(deps): Update vulnerable npm packages
  js/twofactor_totp-main-login-setup.js
  js/twofactor_totp-main-login-setup.js.map
  js/twofactor_totp-main-settings.js
  js/twofactor_totp-main-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1374 [stable25] fix(deps): Update vulnerable npm packages
  js/twofactor_totp-main-login-setup.js
  js/twofactor_totp-main-login-setup.js.map
  js/twofactor_totp-main-settings.js
  js/twofactor_totp-main-settings.js.map
  package-lock.json
Labels: 3. to review

#1384 ci: Do not cancel concurrent acceptance tests
  .github/workflows/test.yml
Labels: 3. to review

#1394 chore(deps-dev): replace vue-jest with @vue/vue2-jest@27
  js/twofactor_totp-main-login-setup.js
  js/twofactor_totp-main-login-setup.js.map
  js/twofactor_totp-main-settings.js
  js/twofactor_totp-main-settings.js.map
  package-lock.json
  package.json
Labels: 4. to release, dependencies
