Repository nextcloud/twofactor_totp, pull requests merged in 2024-02, with the labels that each got.

#1483 fix: reduce secret size to 160 bits
  lib/Service/Totp.php
Labels: 3. to review

#1469 [master] Fix npm audit
  js/twofactor_totp-main-login-setup.js
  js/twofactor_totp-main-login-setup.js.LICENSE.txt
  js/twofactor_totp-main-login-setup.js.map
  js/twofactor_totp-main-settings.js
  js/twofactor_totp-main-settings.js.LICENSE.txt
  js/twofactor_totp-main-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1479 Update npm and node engines versions
  package.json
Labels: dependencies

#1474 [stable28] Fix npm audit
  .github/workflows/test.yml
  js/twofactor_totp-main-login-setup.js
  js/twofactor_totp-main-login-setup.js.LICENSE.txt
  js/twofactor_totp-main-login-setup.js.map
  js/twofactor_totp-main-settings.js
  js/twofactor_totp-main-settings.js.LICENSE.txt
  js/twofactor_totp-main-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1462 [stable27] Fix npm audit
  .github/workflows/test.yml
  js/twofactor_totp-main-login-setup.js
  js/twofactor_totp-main-login-setup.js.map
  js/twofactor_totp-main-settings.js
  js/twofactor_totp-main-settings.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1461 [stable26] Fix npm audit
  js/twofactor_totp-main-login-setup.js
  js/twofactor_totp-main-login-setup.js.LICENSE.txt
  js/twofactor_totp-main-login-setup.js.map
  js/twofactor_totp-main-settings.js
  js/twofactor_totp-main-settings.js.LICENSE.txt
  js/twofactor_totp-main-settings.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1486 ci: block merges during freezes
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review, backport-request

#1490 ci: add compile command workflow
  .github/workflows/command-compile.yml
Labels: 3. to review
